name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test with wasm-pack and Playwright
    runs-on: ubuntu-latest # https://github.com/actions/runner-images?tab=readme-ov-file#available-images
    timeout-minutes: 12 # Even the Coopers' running test is faster than this...

    steps:
      # Checkout the repository, https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Rust, https://github.com/actions-rust-lang/setup-rust-toolchain
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      # Cache Cargo dependencies, https://github.com/actions/cache
      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      # https://rustwasm.github.io/docs/wasm-pack/
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Build with wasm-pack
        run: wasm-pack build --release --target web
      - name: Run wasm-pack test with Firefox
        run: wasm-pack test --headless --firefox

      # Use separate Docker instance, https://github.com/addnab/docker-run-action
      - name: Run Playwright tests in Docker
        uses: addnab/docker-run-action@v3
        with:
          image: mcr.microsoft.com/playwright:v1.48.1-noble
          # More memory to run browser and volume linking
          options: --shm-size=1gb -v ${{ github.workspace }}:/work
          run: |
            cd work
            npm install
            npm test